// ============================================
// 🃏 BANCO DE CARTAS DO CASAL
// 4 tipos: pergunta | acao | declaracao | desafio
// Tom: Rafael + Fernanda — 13 anos, 3 filhos, real
// ============================================

const CARTAS_NORMAIS = [
  // ============ PERGUNTAS (100) ============
  // 1-30: conexão / nosso amor
  { tipo: 'pergunta', msg: 'Qual foi o momento que você percebeu que me amava?' },
  { tipo: 'pergunta', msg: 'O que você mais gosta de fazer quando a gente tá junto?' },
  { tipo: 'pergunta', msg: 'Me conta uma memória nossa que te faz sorrir toda vez' },
  { tipo: 'pergunta', msg: 'Qual foi o dia mais feliz da nossa vida até agora?' },
  { tipo: 'pergunta', msg: 'Se a gente pudesse morar em qualquer lugar, onde seria?' },
  { tipo: 'pergunta', msg: 'Qual hábito meu você acha fofo?' },
  { tipo: 'pergunta', msg: 'Qual hábito meu você acha irritante mas tolera?' },
  { tipo: 'pergunta', msg: 'O que você sentiu no nosso primeiro beijo?' },
  { tipo: 'pergunta', msg: 'Me fala da primeira vez que viu foto minha' },
  { tipo: 'pergunta', msg: 'O que mais te atraiu em mim lá no começo?' },
  { tipo: 'pergunta', msg: 'Qual música nossa te faz chorar?' },
  { tipo: 'pergunta', msg: 'Qual momento nosso você queria reviver?' },
  { tipo: 'pergunta', msg: 'O que a gente faz junto que ninguém mais faz igual?' },
  { tipo: 'pergunta', msg: 'Qual foi a maior prova de amor que eu já te dei?' },
  { tipo: 'pergunta', msg: 'Qual foi a maior prova de amor que VOCÊ já me deu?' },
  { tipo: 'pergunta', msg: 'Se a gente tivesse um dia perfeito sem filhos, como seria?' },
  { tipo: 'pergunta', msg: 'O que eu faço que te faz sentir em casa?' },
  { tipo: 'pergunta', msg: 'O que você mudaria em mim? (sendo honesta)' },
  { tipo: 'pergunta', msg: 'O que você acha que eu mudei pra melhor nesses 13 anos?' },
  { tipo: 'pergunta', msg: 'Qual foi a maior briga nossa e o que aprendemos com ela?' },
  { tipo: 'pergunta', msg: 'Me conta um sonho que você tem e nunca me contou' },
  { tipo: 'pergunta', msg: 'Qual foi a coisa mais engraçada que aconteceu com a gente?' },
  { tipo: 'pergunta', msg: 'Se a gente ganhasse na mega, o que faria primeiro?' },
  { tipo: 'pergunta', msg: 'Qual foi o melhor presente que eu já te dei?' },
  { tipo: 'pergunta', msg: 'Me diz uma coisa que eu faço bem e não percebe' },
  { tipo: 'pergunta', msg: 'O que você mais sente falta de quando a gente tá longe?' },
  { tipo: 'pergunta', msg: 'Qual foi o elogio mais marcante que eu te fiz?' },
  { tipo: 'pergunta', msg: 'Em que momento da nossa vida você se sentiu mais amada?' },
  { tipo: 'pergunta', msg: 'Se a gente fosse personagem de filme, qual seria?' },
  { tipo: 'pergunta', msg: 'Qual sabor de pizza combina mais comigo?' },

  // 31-50: família / filhos / futuro
  { tipo: 'pergunta', msg: 'O que você mais admira em mim como pai/mãe?' },
  { tipo: 'pergunta', msg: 'Dos nossos filhos, quem puxou mais a você?' },
  { tipo: 'pergunta', msg: 'Dos nossos filhos, quem puxou mais a mim?' },
  { tipo: 'pergunta', msg: 'Qual memória dos nossos filhos te emociona mais?' },
  { tipo: 'pergunta', msg: 'Se a gente tivesse mais um filho, queria menino ou menina?' },
  { tipo: 'pergunta', msg: 'O que a gente faz bem como casal que pouca gente faz?' },
  { tipo: 'pergunta', msg: 'Qual tradição nossa você quer manter pra sempre?' },
  { tipo: 'pergunta', msg: 'Me diz uma coisa que você quer fazer com a família toda' },
  { tipo: 'pergunta', msg: 'Daqui a 20 anos, o que você quer que a gente esteja fazendo?' },
  { tipo: 'pergunta', msg: 'Qual viagem você quer fazer com as crianças?' },
  { tipo: 'pergunta', msg: 'Qual foi a fase mais difícil como casal e o que te segurou?' },
  { tipo: 'pergunta', msg: 'O que eu faço que te faz sentir segura?' },
  { tipo: 'pergunta', msg: 'O que eu faço que te faz sentir insegura?' },
  { tipo: 'pergunta', msg: 'Me conta uma coisa que você queria que eu soubesse' },
  { tipo: 'pergunta', msg: 'Qual a maior lição que a gente aprendeu juntos?' },
  { tipo: 'pergunta', msg: 'Se a gente escrevesse um livro, qual seria o título?' },
  { tipo: 'pergunta', msg: 'Qual hobby meu você queria experimentar?' },
  { tipo: 'pergunta', msg: 'Qual hobby seu eu deveria experimentar?' },
  { tipo: 'pergunta', msg: 'Me conta sobre um medo que você tem e eu não sei' },
  { tipo: 'pergunta', msg: 'O que te faz se sentir mais eu mesma?' },

  // 51-80: cotidiano / piadas internas / zoeira
  { tipo: 'pergunta', msg: 'Qual foi a maior besteira que a gente fez junto?' },
  { tipo: 'pergunta', msg: 'Me lembra de uma piada interna nossa que pouca gente entende' },
  { tipo: 'pergunta', msg: 'Se a gente tivesse uma banda, qual seria o nome?' },
  { tipo: 'pergunta', msg: 'Qual comida nossa é a mais gostosa que só a gente sabe fazer?' },
  { tipo: 'pergunta', msg: 'Qual lugar perto de casa a gente nunca foi e devia ir?' },
  { tipo: 'pergunta', msg: 'Qual mania minha você acha mais engraçada?' },
  { tipo: 'pergunta', msg: 'Qual mania sua eu acho mais engraçada?' },
  { tipo: 'pergunta', msg: 'Se a gente fosse preso junto por um dia, o que faria?' },
  { tipo: 'pergunta', msg: 'Qual o apelido carinhoso que você mais gosta que eu te chamo?' },
  { tipo: 'pergunta', msg: 'Qual apelido carinhoso eu te chamo que você ODEIA?' },
  { tipo: 'pergunta', msg: 'Me diz o que eu faço que te dá安全感 (segurança)' },
  { tipo: 'pergunta', msg: 'Qual a coisa mais aleatória que você lembra de mim?' },
  { tipo: 'pergunta', msg: 'Se a gente sumisse por 24h sem avisar, o que faria?' },
  { tipo: 'pergunta', msg: 'Qual foi a última coisa que te fez rir muito?' },
  { tipo: 'pergunta', msg: 'Qual foi a última coisa que te fez chorar de emoção?' },
  { tipo: 'pergunta', msg: 'O que você faria se eu te pedisse em namoro hoje?' },
  { tipo: 'pergunta', msg: 'Qual o cheiro que te lembra de mim?' },
  { tipo: 'pergunta', msg: 'Qual a primeira coisa que você faz quando acorda?' },
  { tipo: 'pergunta', msg: 'O que você faz quando sente saudade minha?' },
  { tipo: 'pergunta', msg: 'Se eu pudesse ler sua mente agora, o que descobriria?' },
  { tipo: 'pergunta', msg: 'Qual foto nossa você mais ama?' },
  { tipo: 'pergunta', msg: 'Qual foto nossa você acha engraçada mas não posta?' },
  { tipo: 'pergunta', msg: 'Me conta de um dia nosso que ninguém mais sabe' },
  { tipo: 'pergunta', msg: 'Qual o maior sonho seu que eu posso te ajudar a realizar?' },
  { tipo: 'pergunta', msg: 'Qual foi o melhor conselho que eu já te dei?' },
  { tipo: 'pergunta', msg: 'Me faz uma pergunta que sempre quis fazer mas nunca fez' },
  { tipo: 'pergunta', msg: 'O que te fez dizer sim pra mim?' },
  { tipo: 'pergunta', msg: 'Qual a coisa que você mais gosta de ouvir de mim?' },
  { tipo: 'pergunta', msg: 'Se a gente ganhasse uma viagem grátis, pra onde ia?' },
  { tipo: 'pergunta', msg: 'Qual hobby novo você quer que a gente comece junto?' },

  // 81-100: reflexão profunda
  { tipo: 'pergunta', msg: 'O que te fez escolher ficar comigo nos momentos difíceis?' },
  { tipo: 'pergunta', msg: 'Qual parte de você eu mais ajudei a descobrir?' },
  { tipo: 'pergunta', msg: 'Em que momento eu te decepcionei e como te reconquistei?' },
  { tipo: 'pergunta', msg: 'O que você quer que eu saiba mas tem vergonha de falar?' },
  { tipo: 'pergunta', msg: 'Se a gente pudesse recomeçar do 01/01/2014, faria diferente?' },
  { tipo: 'pergunta', msg: 'Qual a coisa mais bonita que alguém já disse sobre a gente?' },
  { tipo: 'pergunta', msg: 'Me lembra do dia que você se sentiu mais orgulhosa de mim' },
  { tipo: 'pergunta', msg: 'Se eu sumisse por um ano, o que sentiria falta primeiro?' },
  { tipo: 'pergunta', msg: 'O que você quer que nunca mude em nós?' },
  { tipo: 'pergunta', msg: 'Qual a maior aventura que ainda vamos viver?' },
  { tipo: 'pergunta', msg: 'O que significa "lar" pra você?' },
  { tipo: 'pergunta', msg: 'Me fala da primeira vez que sentiu que eu era o amor da sua vida' },
  { tipo: 'pergunta', msg: 'Qual o seu maior medo de perder de mim?' },
  { tipo: 'pergunta', msg: 'Se eu morresse amanhã, o que gostaria de ter me dito hoje?' },
  { tipo: 'pergunta', msg: 'O que te faz acordar com vontade de viver todo dia?' },
  { tipo: 'pergunta', msg: 'Qual o segredo nosso que vai pro caixão?' },
  { tipo: 'pergunta', msg: 'Me lembra por que casou comigo' },
  { tipo: 'pergunta', msg: 'Qual a coisa que eu faço e que ninguém mais faz igual?' },
  { tipo: 'pergunta', msg: 'Em que momento da vida eu te salvei sem saber?' },
  { tipo: 'pergunta', msg: 'O que te faz se apaixonar por mim de novo toda semana?' },

  // ============ AÇÕES (100) ============
  // 1-30: carinho / fofo
  { tipo: 'acao', msg: 'Me faz um cafuné por 1 minuto sem parar' },
  { tipo: 'acao', msg: 'Me dá um abraço apertado de 30 segundos' },
  { tipo: 'acao', msg: 'Me dá um beijo na testa agora' },
  { tipo: 'acao', msg: 'Fala "eu te amo" do jeito mais sincero que conseguir' },
  { tipo: 'acao', msg: 'Me olha nos olhos por 1 minuto sem rir' },
  { tipo: 'acao', msg: 'Diz uma coisa que ama em mim que nunca disse' },
  { tipo: 'acao', msg: 'Me faz um carinho no cabelo' },
  { tipo: 'acao', msg: 'Pega na minha mão e aperta com carinho' },
  { tipo: 'acao', msg: 'Me dá um beijo de boa noite como se fosse o último' },
  { tipo: 'acao', msg: 'Faz minha comida favorita nos próximos dias' },
  { tipo: 'acao', msg: 'Me faz um café na cama amanhã' },
  { tipo: 'acao', msg: 'Me manda uma mensagem fofa do nada hoje' },
  { tipo: 'acao', msg: 'Dança comigo a música que for tocar agora' },
  { tipo: 'acao', msg: 'Me dá um beijo na bochecha' },
  { tipo: 'acao', msg: 'Canta uma música nossa agora' },
  { tipo: 'acao', msg: 'Me dá um abraço de urso' },
  { tipo: 'acao', msg: 'Sussurra "eu te amo" no meu ouvido' },
  { tipo: 'acao', msg: 'Faz um desenho meu em 1 minuto' },
  { tipo: 'acao', msg: 'Me escreve um bilhetinho carinhoso agora' },
  { tipo: 'acao', msg: 'Me dá um beijo estalado' },
  { tipo: 'acao', msg: 'Me faz cócegas até eu rir' },
  { tipo: 'acao', msg: 'Coloca a mão no meu coração e fica assim por 30s' },
  { tipo: 'acao', msg: 'Me chama pelo apelido mais fofo que tem' },
  { tipo: 'acao', msg: 'Me dá 3 beijinhos onde quiser' },
  { tipo: 'acao', msg: 'Me faz uma massagem nos ombros' },
  { tipo: 'acao', msg: 'Me dá uma cheirada no pescoço' },
  { tipo: 'acao', msg: 'Acaricia meu rosto com a mão' },
  { tipo: 'acao', msg: 'Me manda um áudio fofo agora' },
  { tipo: 'acao', msg: 'Senta do meu lado bem pertinho por 5 min sem celular' },
  { tipo: 'acao', msg: 'Faz minha cara de boba e manda foto' },

  // 31-60: atenção / cuidado
  { tipo: 'acao', msg: 'Me lembra do seu melhor momento comigo hoje' },
  { tipo: 'acao', msg: 'Me diz o que eu fiz essa semana que te marcou' },
  { tipo: 'acao', msg: 'Me conta uma coisa que tava engasgada' },
  { tipo: 'acao', msg: 'Me pede desculpa por algo que ficou pendente' },
  { tipo: 'acao', msg: 'Me perdoa por algo que ficou pendente' },
  { tipo: 'acao', msg: 'Me diz uma coisa que admira em mim' },
  { tipo: 'acao', msg: 'Me lista 5 coisas que ama em mim' },
  { tipo: 'acao', msg: 'Me diz o que faria diferente se voltasse no tempo' },
  { tipo: 'acao', msg: 'Me dá uma sugestão pra melhorar a gente' },
  { tipo: 'acao', msg: 'Me conta um sonho que teve comigo' },
  { tipo: 'acao', msg: 'Planeja um encontro surpresa pra próxima semana' },
  { tipo: 'acao', msg: 'Me prepara um banho quente agora' },
  { tipo: 'acao', msg: 'Me espera com o jantar pronto' },
  { tipo: 'acao', msg: 'Lava a louça pra mim hoje' },
  { tipo: 'acao', msg: 'Me cobre com o cobertor se eu tiver com sono' },
  { tipo: 'acao', msg: 'Coloca a música que a gente ama pra tocar' },
  { tipo: 'acao', msg: 'Me dá bom dia com um beijo amanhã' },
  { tipo: 'acao', msg: 'Me liga só pra ouvir minha voz' },
  { tipo: 'acao', msg: 'Me faz um vídeo fofo agora' },
  { tipo: 'acao', msg: 'Me manda um meme que te lembrou de mim' },
  { tipo: 'acao', msg: 'Me conta uma piada nova' },
  { tipo: 'acao', msg: 'Me faz rir com a melhor cara de bobo' },
  { tipo: 'acao', msg: 'Me abraça por trás sem avisar' },
  { tipo: 'acao', msg: 'Me dá um high-five carinhoso' },
  { tipo: 'acao', msg: 'Me faz companhia enquanto eu faço algo chato' },
  { tipo: 'acao', msg: 'Me ajuda com uma tarefa que eu tô precisando' },
  { tipo: 'acao', msg: 'Me lembra de tomar água' },
  { tipo: 'acao', msg: 'Me faz um elogio específico (não genérico)' },
  { tipo: 'acao', msg: 'Diz meu nome completo do jeito que só você fala' },
  { tipo: 'acao', msg: 'Me faz sentir especial por 1 minuto inteiro' },

  // 61-80: prático / divertido
  { tipo: 'acao', msg: 'Tira uma foto espontânea nossa agora' },
  { tipo: 'acao', msg: 'Marca um date só nosso pra esse fim de semana' },
  { tipo: 'acao', msg: 'Me ensina algo que você sabe fazer' },
  { tipo: 'acao', msg: 'Deixa eu te ensinar algo' },
  { tipo: 'acao', msg: 'Me conta uma história da sua infância' },
  { tipo: 'acao', msg: 'Me mostra a foto mais antiga do seu celular' },
  { tipo: 'acao', msg: 'Joga um jogo que a gente nunca jogou' },
  { tipo: 'acao', msg: 'Cozinha algo diferente comigo' },
  { tipo: 'acao', msg: 'Vai caminhar comigo sem celular' },
  { tipo: 'acao', msg: 'Me mostra sua playlist de músicas nossas' },
  { tipo: 'acao', msg: 'Desenha um coração no meu braço com caneta' },
  { tipo: 'acao', msg: 'Me dá um pedaço de chocolate (mesmo querendo pra si)' },
  { tipo: 'acao', msg: 'Me deixa escolher o filme hoje' },
  { tipo: 'acao', msg: 'Me lê uma mensagem antiga bonita que eu te mandei' },
  { tipo: 'acao', msg: 'Me mostra o que te faz feliz ultimamente' },
  { tipo: 'acao', msg: 'Vem deitar comigo 5 minutinhos sem falar nada' },
  { tipo: 'acao', msg: 'Me deixa pentear seu cabelo' },
  { tipo: 'acao', msg: 'Me faz uma surpresa simples hoje' },
  { tipo: 'acao', msg: 'Faz uma lista de "10 coisas que amo em nós"' },
  { tipo: 'acao', msg: 'Me dá um beijo de uma forma que nunca tenha dado' },

  // 81-100: ousadas (não-sexual)
  { tipo: 'acao', msg: 'Me dá um beijo de cinema agora' },
  { tipo: 'acao', msg: 'Tira a roupa e fica só de lingerie/ cueca por 1 min' },
  { tipo: 'acao', msg: 'Faz um strip-tease de 30 segundos' },
  { tipo: 'acao', msg: 'Me mostra a foto mais provocante do seu celular' },
  { tipo: 'acao', msg: 'Me sussurra algo safado no ouvido' },
  { tipo: 'acao', msg: 'Faz um charme pra mim como se fosse a 1ª vez' },
  { tipo: 'acao', msg: 'Me dá um banho de beijo no pescoço' },
  { tipo: 'acao', msg: 'Me puxa pra dançar coladinho agora' },
  { tipo: 'acao', msg: 'Faz uma massagem nos meus pés' },
  { tipo: 'acao', msg: 'Me beija como se fosse o último beijo' },
  { tipo: 'acao', msg: 'Fala uma fantasia que sempre quis realizar' },
  { tipo: 'acao', msg: 'Tira uma foto sensual e me manda' },
  { tipo: 'acao', msg: 'Me deixa escolher sua roupa amanhã' },
  { tipo: 'acao', msg: 'Faz uma declaração de amor no espelho pra eu filmar' },
  { tipo: 'acao', msg: 'Me beija em público hoje' },
  { tipo: 'acao', msg: 'Fala meu nome com voz sensual' },
  { tipo: 'acao', msg: 'Me dá um beijo demorado de cinema' },
  { tipo: 'acao', msg: 'Faz carinho no meu corpo todo (sem pressa)' },
  { tipo: 'acao', msg: 'Me seduz como se a gente tivesse se conhecendo agora' },
  { tipo: 'acao', msg: 'Me chama pra um "date noturno" surpresa' },

  // ============ DECLARAÇÕES (100) ============
  // 1-40: declarações clássicas
  { tipo: 'declaracao', msg: 'Você é o amor da minha vida. Sempre foi.' },
  { tipo: 'declaracao', msg: 'Eu te amo mais hoje do que ontem. E amanhã vai ser mais ainda.' },
  { tipo: 'declaracao', msg: 'Se eu pudesse escolher de novo, escolheria você mil vezes.' },
  { tipo: 'declaracao', msg: 'Você me faz uma pessoa melhor só por existir.' },
  { tipo: 'declaracao', msg: '13 anos e eu ainda me apaixono por você toda semana.' },
  { tipo: 'declaracao', msg: 'Nosso amor é a coisa mais bonita da minha vida.' },
  { tipo: 'declaracao', msg: 'Você é meu lar, meu chão, meu tudo.' },
  { tipo: 'declaracao', msg: 'Quando tudo dá errado, você é minha constante.' },
  { tipo: 'declaracao', msg: 'Você é a mulher mais incrível que eu já conheci.' },
  { tipo: 'declaracao', msg: 'Você me faz acreditar que pra sempre é pouco tempo.' },
  { tipo: 'declaracao', msg: 'Meu lugar favorito no mundo é do seu lado.' },
  { tipo: 'declaracao', msg: 'Obrigado(a) por me escolher todos os dias.' },
  { tipo: 'declaracao', msg: 'Você é mais do que eu mereço. E eu agradeço por isso.' },
  { tipo: 'declaracao', msg: 'Nosso "eu te amo" é o mesmo desde 2014. E continua crescendo.' },
  { tipo: 'declaracao', msg: 'Você é a melhor parte de mim.' },
  { tipo: 'declaracao', msg: 'Cada memória contigo vale uma vida inteira.' },
  { tipo: 'declaracao', msg: 'Amo seu jeito, suas manias, seu tudo.' },
  { tipo: 'declaracao', msg: 'Você é meu sonho que virou realidade.' },
  { tipo: 'declaracao', msg: 'Eu te amo até quando você me irrita. Sobretudo quando me irrita.' },
  { tipo: 'declaracao', msg: 'Você é minha pessoa favorita no mundo inteiro.' },
  { tipo: 'declaracao', msg: 'Obrigado(a) por me fazer rir mesmo quando eu quero chorar.' },
  { tipo: 'declaracao', msg: 'Você me faz acreditar em amor de verdade.' },
  { tipo: 'declaracao', msg: 'Se eu tivesse que começar de novo, queria que tudo fosse igual, só com você.' },
  { tipo: 'declaracao', msg: 'Amo como você cuida da nossa família.' },
  { tipo: 'declaracao', msg: 'Amo como você me faz sentir seguro(a).' },
  { tipo: 'declaracao', msg: 'Você me completa de um jeito que ninguém mais consegue.' },
  { tipo: 'declaracao', msg: 'Quando te olho, ainda vejo a pessoa do dia 01/01/2014.' },
  { tipo: 'declaracao', msg: 'Meu coração é seu. Sempre foi.' },
  { tipo: 'declaracao', msg: 'Você é o melhor presente que a vida me deu.' },
  { tipo: 'declaracao', msg: 'Amo nossa casa, nossos filhos, nossa vida. Mas amo mais você.' },
  { tipo: 'declaracao', msg: 'Você é minha paz no meio do caos.' },
  { tipo: 'declaracao', msg: 'Cada dia contigo é um presente que eu desembrulho de novo.' },
  { tipo: 'declaracao', msg: 'Eu te amo não pelo que você é, mas pelo que eu sou quando tô com você.' },
  { tipo: 'declaracao', msg: 'Você é minha história favorita de contar.' },
  { tipo: 'declaracao', msg: 'Se eu pudesse parar o tempo, seria em qualquer momento contigo.' },
  { tipo: 'declaracao', msg: 'Obrigado(a) por existir.' },
  { tipo: 'declaracao', msg: 'Você é meu "pra sempre".' },
  { tipo: 'declaracao', msg: 'Mesmo depois de 13 anos, você me faz borboletas no estômago.' },
  { tipo: 'declaracao', msg: 'Amo mais do que palavras conseguem dizer.' },
  { tipo: 'declaracao', msg: 'Você me faz acreditar que almas gêmeas existem.' },
  { tipo: 'declaracao', msg: 'Meu amor por você é minha coisa mais certa no mundo.' },

  // 41-70: razões pelas quais
  { tipo: 'declaracao', msg: 'Te amo porque você me faz rir quando eu tô pra baixo.' },
  { tipo: 'declaracao', msg: 'Te amo porque você me conhece melhor que ninguém.' },
  { tipo: 'declaracao', msg: 'Te amo pelo seu cheiro, sua voz, seu toque.' },
  { tipo: 'declaracao', msg: 'Te amo porque você me deixa ser eu mesmo.' },
  { tipo: 'declaracao', msg: 'Te amo porque me faz querer ser uma pessoa melhor.' },
  { tipo: 'declaracao', msg: 'Te amo porque você cuida de mim quando eu não consigo.' },
  { tipo: 'declaracao', msg: 'Te amo porque me olha como se eu fosse o melhor do mundo.' },
  { tipo: 'declaracao', msg: 'Te amo porque você é parceira nos altos e baixos.' },
  { tipo: 'declaracao', msg: 'Te amo porque você me ensinou o que é amor de verdade.' },
  { tipo: 'declaracao', msg: 'Te amo porque me apoia até nas minhas loucuras.' },
  { tipo: 'declaracao', msg: 'Te amo porque ri das minhas piadas ruins.' },
  { tipo: 'declaracao', msg: 'Te amo porque me dá razão quando eu tô certo(a) e razão quando tô errado.' },
  { tipo: 'declaracao', msg: 'Te amo porque me faz sentir em casa em qualquer lugar.' },
  { tipo: 'declaracao', msg: 'Te amo porque não desiste da gente, nunca.' },
  { tipo: 'declaracao', msg: 'Te amo porque me faz acreditar que tudo vai dar certo.' },
  { tipo: 'declaracao', msg: 'Te amo porque tem paciência com minhas manias.' },
  { tipo: 'declaracao', msg: 'Te amo porque me faz companhia no silêncio.' },
  { tipo: 'declaracao', msg: 'Te amo porque me entende sem eu precisar explicar.' },
  { tipo: 'declaracao', msg: 'Te amo porque me faz sentir especial todo dia.' },
  { tipo: 'declaracao', msg: 'Te amo porque me vê como pessoa, não como projeto.' },
  { tipo: 'declaracao', msg: 'Te amo porque me dá espaço pra ser vulnerável.' },
  { tipo: 'declaracao', msg: 'Te amo porque é minha melhor amiga.' },
  { tipo: 'declaracao', msg: 'Te amo porque me faz querer voltar pra casa.' },
  { tipo: 'declaracao', msg: 'Te amo porque me faz orgulhoso(a) de ser seu(sua).' },
  { tipo: 'declaracao', msg: 'Te amo porque tem o dom de me acalmar.' },
  { tipo: 'declaracao', msg: 'Te amo porque é parceira de zoeira.' },
  { tipo: 'declaracao', msg: 'Te amo porque me faz acreditar em futuro.' },
  { tipo: 'declaracao', msg: 'Te amo porque me dá安全感 (segurança) total.' },
  { tipo: 'declaracao', msg: 'Te amo porque me faz sentir amado sem precisar de palavras.' },
  { tipo: 'declaracao', msg: 'Te amo porque me respeita.' },

  // 71-100: promessas
  { tipo: 'declaracao', msg: 'Prometo te amar nos dias bons E nos ruins.' },
  { tipo: 'declaracao', msg: 'Prometo te escolher todo dia, mesmo quando for fácil escolher outro.' },
  { tipo: 'declaracao', msg: 'Prometo te fazer rir pelo resto da vida.' },
  { tipo: 'declaracao', msg: 'Prometo te dar a mão nos momentos difíceis.' },
  { tipo: 'declaracao', msg: 'Prometo te lembrar do nosso amor quando você esquecer.' },
  { tipo: 'declaracao', msg: 'Prometo te abraçar mesmo quando você brigar comigo.' },
  { tipo: 'declaracao', msg: 'Prometo te falar "eu te amo" todo dia, mesmo quando parecer óbvio.' },
  { tipo: 'declaracao', msg: 'Prometo te dar motivos pra sorrir sempre.' },
  { tipo: 'declaracao', msg: 'Prometo te surpreender de vez em quando.' },
  { tipo: 'declaracao', msg: 'Prometo te defender de qualquer coisa.' },
  { tipo: 'declaracao', msg: 'Prometo te apoiar em todos os seus sonhos.' },
  { tipo: 'declaracao', msg: 'Prometo te dar carinho mesmo quando eu tiver cansado.' },
  { tipo: 'declaracao', msg: 'Prometo te olhar do mesmo jeito daqui 30 anos.' },
  { tipo: 'declaracao', msg: 'Prometo ser sua casa quando o mundo lá fora for pesado.' },
  { tipo: 'declaracao', msg: 'Prometo te dar orgulho de mim.' },
  { tipo: 'declaracao', msg: 'Prometo te fazer companhia até na velhice.' },
  { tipo: 'declaracao', msg: 'Prometo te fazer sentir desejada(o).' },
  { tipo: 'declaracao', msg: 'Prometo te ouvir quando você precisar falar.' },
  { tipo: 'declaracao', msg: 'Prometo te dar tempo quando você precisar de espaço.' },
  { tipo: 'declaracao', msg: 'Prometo te fazer rir quando o mundo parecer sem graça.' },
  { tipo: 'declaracao', msg: 'Prometo te amar mais do que ontem, menos do que amanhã.' },
  { tipo: 'declaracao', msg: 'Prometo ser o motivo do seu sorriso.' },
  { tipo: 'declaracao', msg: 'Prometo te fazer feliz pelo resto dos meus dias.' },
  { tipo: 'declaracao', msg: 'Prometo te lembrar do que a gente tem quando vier dúvida.' },
  { tipo: 'declaracao', msg: 'Prometo nunca desistir da gente.' },
  { tipo: 'declaracao', msg: 'Prometo te dar uma vida cheia de amor.' },
  { tipo: 'declaracao', msg: 'Prometo ser seu melhor amigo(a) antes de qualquer coisa.' },
  { tipo: 'declaracao', msg: 'Prometo te fazer o cônjuge mais feliz do mundo.' },
  { tipo: 'declaracao', msg: 'Prometo ser seu porto seguro sempre.' },
  { tipo: 'declaracao', msg: 'Prometo te amar com tudo que tenho, todos os dias, pra sempre.' },

  // ============ DESAFIOS (50) ============
  // 1-20: fofos
  { tipo: 'desafio', msg: 'Fique 5 minutos sem tocar no celular quando estiver comigo(a)' },
  { tipo: 'desafio', msg: 'Cozinhe uma receita nova pra nós essa semana' },
  { tipo: 'desafio', msg: 'Me surpreenda com algo sem motivo' },
  { tipo: 'desafio', msg: 'Passe 24h sem reclamar de nada' },
  { tipo: 'desafio', msg: 'Me diga 3 coisas que te orgulham em mim antes de dormir' },
  { tipo: 'desafio', msg: 'Me faça rir por 1 minuto seguido' },
  { tipo: 'desafio', msg: 'Tire uma foto bonita nossa hoje' },
  { tipo: 'desafio', msg: 'Escreva um bilhetinho e esconda pra eu achar' },
  { tipo: 'desafio', msg: 'Me mande uma foto antiga nossa por mensagem' },
  { tipo: 'desafio', msg: 'Ligue pra mim só pra dizer "oi" agora' },
  { tipo: 'desafio', msg: 'Me dê 5 motivos pra te amar agora' },
  { tipo: 'desafio', msg: 'Dance comigo 1 música mesmo sem querer' },
  { tipo: 'desafio', msg: 'Planeje um encontro surpresa' },
  { tipo: 'desafio', msg: 'Me escreva uma carta de amor essa semana' },
  { tipo: 'desafio', msg: 'Me faça o pedido de namoro de novo' },
  { tipo: 'desafio', msg: 'Me cante uma música' },
  { tipo: 'desafio', msg: 'Diga "eu te amo" em 3 línguas diferentes' },
  { tipo: 'desafio', msg: 'Faça uma declaração de amor em público' },
  { tipo: 'desafio', msg: 'Me faça um café da manhã na cama' },
  { tipo: 'desafio', msg: 'Me dê um dia livre de responsabilidade (faça tudo)' },

  // 21-35: ousados fofos
  { tipo: 'desafio', msg: 'Me mande uma foto de quando se arruma pra me ver' },
  { tipo: 'desafio', msg: 'Me ligue e cante uma música' },
  { tipo: 'desafio', msg: 'Me mande um áudio sussurrando "eu te amo"' },
  { tipo: 'desafio', msg: 'Me faça uma serenata' },
  { tipo: 'desafio', msg: 'Me espere na porta com um beijo hoje' },
  { tipo: 'desafio', msg: 'Fique 1 hora sem celular comigo(a)' },
  { tipo: 'desafio', msg: 'Me dê 10 beijinhos onde eu quiser' },
  { tipo: 'desafio', msg: 'Me faça uma massagem de 15 minutos' },
  { tipo: 'desafio', msg: 'Me dê um beijo em cada dedo da mão' },
  { tipo: 'desafio', msg: 'Me carregue no colo' },
  { tipo: 'desafio', msg: 'Me dê um nome novo carinhoso e use por 1 dia' },
  { tipo: 'desafio', msg: 'Me faça uma lista de 10 razões pra me amar' },
  { tipo: 'desafio', msg: 'Me mande uma mensagem a cada hora por 6h seguidas' },
  { tipo: 'desafio', msg: 'Me faça uma surpresa antes de dormir' },
  { tipo: 'desafio', msg: 'Me diga algo que nunca disse em voz alta' },

  // 36-50: apimentados (ainda não 18+)
  { tipo: 'desafio', msg: 'Me mande uma foto sensual no zap' },
  { tipo: 'desafio', msg: 'Me faça um strip-tease de 30 segundos' },
  { tipo: 'desafio', msg: 'Me dê um beijo francês de 1 minuto' },
  { tipo: 'desafio', msg: 'Fique só de lingerie/cueca por 1 hora' },
  { tipo: 'desafio', msg: 'Me deixe escolher o que você veste amanhã' },
  { tipo: 'desafio', msg: 'Me faça uma massagem com óleo' },
  { tipo: 'desafio', msg: 'Me beije em 5 lugares diferentes' },
  { tipo: 'desafio', msg: 'Me dê um banho de carinho' },
  { tipo: 'desafio', msg: 'Me conte uma fantasia que você tem' },
  { tipo: 'desafio', msg: 'Me leve pra um lugar romântico essa semana' },
  { tipo: 'desafio', msg: 'Me faça companhia no banho' },
  { tipo: 'desafio', msg: 'Me dê um nome sensual e use por um dia' },
  { tipo: 'desafio', msg: 'Me mande uma mensagem APIMENTADA por dia essa semana' },
  { tipo: 'desafio', msg: 'Me seduza como se fosse a 1ª vez' },
  { tipo: 'desafio', msg: 'Fique em silêncio, me olhe, e me beije' }
];

// ============ BANCO 18+ (80 cartas) ============
const CARTAS_18 = [
  // PERGUNTAS 18+ (20)
  { tipo: 'pergunta', msg: 'Qual parte do meu corpo te deixa mais louco(a)?' },
  { tipo: 'pergunta', msg: 'Qual fantasia você tem e nunca me contou?' },
  { tipo: 'pergunta', msg: 'O que te deixa mais excitado(a) em mim?' },
  { tipo: 'pergunta', msg: 'Me conta o que passou pela sua cabeça na 1ª vez que me viu' },
  { tipo: 'pergunta', msg: 'Qual foi a melhor noite que a gente já transou?' },
  { tipo: 'pergunta', msg: 'Onde é o lugar mais ousado que você faria amor comigo?' },
  { tipo: 'pergunta', msg: 'O que você quer que eu faça mais na cama?' },
  { tipo: 'pergunta', msg: 'Qual posição favorita nossa?' },
  { tipo: 'pergunta', msg: 'Me conta uma coisa que eu faço na cama que te enlouquece' },
  { tipo: 'pergunta', msg: 'Qual parte do meu corpo você beija primeiro mentalmente?' },
  { tipo: 'pergunta', msg: 'Você prefere manhã, tarde ou noite pra momento a dois?' },
  { tipo: 'pergunta', msg: 'O que te excita mais: falar sujo ou ser surpreso(a)?' },
  { tipo: 'pergunta', msg: 'Me conta a fantasia mais safada que você já teve' },
  { tipo: 'pergunta', msg: 'Qual lingerie/roupa íntima minha te deixa maluco(a)?' },
  { tipo: 'pergunta', msg: 'Me descreve o que te faria perder o controle agora' },
  { tipo: 'pergunta', msg: 'Qual música te excita?' },
  { tipo: 'pergunta', msg: 'O que você mais gosta que eu faça com a boca?' },
  { tipo: 'pergunta', msg: 'Você gosta de dominar ou ser dominado(a)?' },
  { tipo: 'pergunta', msg: 'Qual cenário erótico você sempre quis viver?' },
  { tipo: 'pergunta', msg: 'Me conta o que te faria gozar em menos de 5 minutos' },

  // AÇÕES 18+ (25)
  { tipo: 'acao', msg: 'Me tira a roupa com a boca' },
  { tipo: 'acao', msg: 'Me sussurra o que vai fazer antes de fazer' },
  { tipo: 'acao', msg: 'Me beija no pescoço por 1 minuto' },
  { tipo: 'acao', msg: 'Me lambe onde quiser' },
  { tipo: 'acao', msg: 'Me dá um beijo francês de 2 minutos' },
  { tipo: 'acao', msg: 'Tira toda sua roupa e fica pelado(a) por 1 min na minha frente' },
  { tipo: 'acao', msg: 'Me mostra como se masturba (ou me deixa ver)' },
  { tipo: 'acao', msg: 'Faz um strip-tease pra mim com a música que eu escolher' },
  { tipo: 'acao', msg: 'Me amassa com vontade' },
  { tipo: 'acao', msg: 'Me morde de leve no pescoço' },
  { tipo: 'acao', msg: 'Me provoca por 5 minutos sem me deixar gozar' },
  { tipo: 'acao', msg: 'Me seduz usando só lingerie/cueca' },
  { tipo: 'acao', msg: 'Me dá um oral agora' },
  { tipo: 'acao', msg: 'Me pede pra fazer amor com a maior voz de desejo que conseguir' },
  { tipo: 'acao', msg: 'Faz o que quiser comigo nos próximos 10 min' },
  { tipo: 'acao', msg: 'Me fode/devora como se fosse a 1ª vez' },
  { tipo: 'acao', msg: 'Me fala todos os meus nomes que te fazem gozar' },
  { tipo: 'acao', msg: 'Me provoca com os dedos antes de ir pra cama' },
  { tipo: 'acao', msg: 'Me beija em 10 lugares diferentes do corpo' },
  { tipo: 'acao', msg: 'Me amarraria (ou deixaria eu te amarrar) com prazer' },
  { tipo: 'acao', msg: 'Me lambe o corpo todo de baixo pra cima' },
  { tipo: 'acao', msg: 'Faz um oral demorado com vontade' },
  { tipo: 'acao', msg: 'Me usa pra se satisfazer como quiser agora' },
  { tipo: 'acao', msg: 'Me goza no rosto/peito (se topar)' },
  { tipo: 'acao', msg: 'Me grava gemendo (privado, só pra nós)' },

  // DECLARAÇÕES 18+ (15)
  { tipo: 'declaracao', msg: 'Você me faz perder o controle.' },
  { tipo: 'declaracao', msg: 'Seu corpo me enlouquece.' },
  { tipo: 'declaracao', msg: 'Eu poderia te fazer amor pra sempre.' },
  { tipo: 'declaracao', msg: 'Seu cheiro me deixa louco(a).' },
  { tipo: 'declaracao', msg: 'Você é a pessoa mais sexy que eu já vi.' },
  { tipo: 'declaracao', msg: 'Quando você me olha, eu fico sem ar.' },
  { tipo: 'declaracao', msg: 'Quero fazer amor com você HOJE.' },
  { tipo: 'declaracao', msg: 'Você me faz querer mais e mais.' },
  { tipo: 'declaracao', msg: 'Seu gemido é meu som favorito.' },
  { tipo: 'declaracao', msg: 'Você me faz sentir o mais desejado(a) do mundo.' },
  { tipo: 'declaracao', msg: 'Cada vez que transamos é melhor que a anterior.' },
  { tipo: 'declaracao', msg: 'Você me deixa com vontade 24h por dia.' },
  { tipo: 'declaracao', msg: 'Seu corpo é meu lugar favorito.' },
  { tipo: 'declaracao', msg: 'Quero acordar e fazer amor com você.' },
  { tipo: 'declaracao', msg: 'Você me faz sentir vivo(a) como ninguém.' },

  // DESAFIOS 18+ (20)
  { tipo: 'desafio', msg: 'Me mande uma foto NU(A) no zap AGORA' },
  { tipo: 'desafio', msg: 'Me mande um áudio gemendo meu nome' },
  { tipo: 'desafio', msg: 'Faça amor comigo em um lugar da casa que a gente nunca usou' },
  { tipo: 'desafio', msg: 'Fique 24h sem roupa dentro de casa (só nós dois)' },
  { tipo: 'desafio', msg: 'Me seduza com lingerie/cueca nova' },
  { tipo: 'desafio', msg: 'Me amasse com vontade em público (em casa com visitas)' },
  { tipo: 'desafio', msg: 'Fique pelado(a) na minha frente por 5 min fazendo coisas do dia a dia' },
  { tipo: 'desafio', msg: 'Me dê um oral de 5 minutos sem parar' },
  { tipo: 'desafio', msg: 'Me provoque até eu implorar' },
  { tipo: 'desafio', msg: 'Faz amor comigo com a luz acesa' },
  { tipo: 'desafio', msg: 'Me amarraria/seria amarrado(a) hoje' },
  { tipo: 'desafio', msg: 'Me faz um oral enquanto eu assisto' },
  { tipo: 'desafio', msg: 'Me seduz durante o jantar (em casa)' },
  { tipo: 'desafio', msg: 'Me faz um strip-tease com a música que EU escolher' },
  { tipo: 'desafio', msg: 'Me faz gozar de um jeito novo' },
  { tipo: 'desafio', msg: 'Me liga e me diz o que vai fazer quando eu chegar em casa' },
  { tipo: 'desafio', msg: 'Me faz um oral recíproco (69) por 5 min' },
  { tipo: 'desafio', msg: 'Me faz um vídeo SEXY (privado) e me manda' },
  { tipo: 'desafio', msg: 'Me usa como quiser por 1 hora' },
  { tipo: 'desafio', msg: 'Me surpreenda com um brinquedo novo hoje' }
];
