// ============================================
// MENSAGENS — 365 mensagens (uma pra cada dia do ano)
// O site pega a mensagem baseado no dia do ano (1-365)
// ============================================

const MENSAGENS = [
  // Janeiro
  "Cada dia ao seu lado é um presente que eu não merecia, mas agradeço todo dia. 💕",
  "Você é a melhor parte do meu dia, todo dia.",
  "Se eu pudesse escolher de novo, escolheria você mil vezes.",
  "Amar você é fácil. Difícil é não te amar cada vez mais.",
  "Seu sorriso é meu lugar favorito no mundo.",
  "Hoje eu acordei pensando em você. De novo. E amanhã vai ser igual.",
  "Você é meu lar, mesmo quando está longe.",
  "Prometo ser seu porto seguro, hoje e sempre.",
  "Cada momento com você vale por uma vida inteira.",
  "Te amar é a coisa mais bonita que já me aconteceu.",
  "Você faz meu mundo ser mais bonito só de existir.",
  "Amo como você me faz rir sem nem tentar.",
  "Obrigado(a) por ser exatamente quem você é.",
  "Você é meu hoje e todos os meus amanhãs.",
  "Se eu pudesse pausar o tempo, escolheria um momento com você.",
  "Meu coração é seu desde aquele dia.",
  "Você é a resposta pra todas as minhas orações.",
  "Dormir e acordar pensando em você é o melhor hábito que tenho.",
  "Cada 'eu te amo' meu é mais verdadeiro que o anterior.",
  "Você é meu sol nos dias cinzas.",
  "Nada no mundo se compara ao que sinto por você.",
  "Obrigado(a) por ser meu parceiro(a) de vida.",
  "Você é a pessoa mais incrível que eu conheço.",
  "Nosso amor é minha coisa favorita no mundo.",
  "Te amar é a melhor decisão que já tomei.",
  "Cada dia com você é uma nova aventura.",
  "Você me faz acreditar em amor de verdade.",
  "Meu lugar favorito é do seu lado.",
  "Quando estou com você, tudo faz sentido.",
  "Obrigado(a) por cada sorriso que você me deu.",
  "Te amo mais do que palavras podem dizer.",

  // Fevereiro (com mensagens extras pelo dia dos namorados)
  "Fevereiro é o mês do amor, mas pra mim é só mais um mês do seu lado.",
  "Dia dos namorados é todo dia quando se ama de verdade. Mas hoje eu te amo mais ainda. 💘",
  "Você não é só meu amor, é meu melhor amigo, meu confidente, meu tudo.",
  "Nosso amor é maior que qualquer data no calendário.",
  "Obrigado(a) por transformar minha vida em um conto de fadas.",
  "Cada beijo seu é o melhor beijo.",
  "Você é a pessoa com quem eu quero envelhecer.",
  "Prometo te amar não só hoje, mas todos os dias da minha vida.",
  "Você é meu Valentine todo dia, não só hoje.",
  "Te amar é a melhor parte de ser eu.",
  "Você é meu para sempre favorito.",
  "Nossa história é a minha preferida.",
  "Eu escolheria você de novo, em qualquer vida, em qualquer mundo. 💕",
  "Você me faz acreditar que almas gêmeas existem.",
  "Te amo do jeito mais bonito que eu sei amar.",
  "Com você, cada dia é dia dos namorados.",
  "Você me completa de um jeito que ninguém mais consegue.",
  "Nosso amor é minha inspiração diária.",
  "Te amo mais hoje do que ontem. Menos do que amanhã.",
  "Você é a melhor coisa que já me aconteceu.",
  "Se amar você é loucura, então eu sou completamente louco(a).",
  "Cada 'eu te amo' é pouco pra expressar o que sinto.",
  "Você é o amor da minha vida, sempre será.",
  "Obrigado(a) por ser meu presente todos os dias.",
  "Você é minha pessoa favorita no mundo inteiro.",
  "Não existe distância que diminua o que sinto por você.",
  "Te amar é o que eu sei fazer de melhor.",
  "Você faz meu coração sorrir.",

  // Março
  "Março chegou e meu amor por você só cresce.",
  "Cada manhã com você é um novo começo.",
  "Você é meu pensamento favorito.",
  "Obrigado(a) por ser minha paz.",
  "Te amo mais do que ontem, sempre.",
  "Você é a melhor coisa que já me aconteceu.",
  "Amo estar com você, mesmo em silêncio.",
  "Você transforma dias comuns em dias especiais.",
  "Nosso amor é minha força.",
  "Com você, tudo é mais leve.",
  "Você é meu motivo pra sorrir.",
  "Cada memória com você é um tesouro.",
  "Te amar é o melhor presente que a vida me deu.",
  "Você me faz acreditar em finais felizes.",
  "Nosso amor é pra sempre, sem prazo de validade.",
  "Você é meu tudo, literalmente.",
  "Quando o mundo é difícil, você é meu refúgio.",
  "Te amo de um jeito que não cabe no peito.",
  "Cada dia com você é um presente de Deus.",
  "Você é a pessoa mais importante da minha vida.",
  "Nosso amor é a coisa mais bonita que eu tenho.",
  "Te amo hoje, amanhã e sempre.",
  "Você me faz querer ser uma pessoa melhor.",
  "Cada momento do seu lado vale ouro.",
  "Você é meu para sempre.",
  "Te amar foi a melhor decisão da minha vida.",
  "Você é a luz que ilumina meus dias.",
  "Nosso amor é forte, bonito e verdadeiro.",
  "Cada abraço seu é meu lugar favorito.",
  "Te amo mais do que tudo que existe.",
  "Você é meu sonho que virou realidade.",

  // Abril
  "Abril, e meu amor por você continua florescendo.",
  "Você é minha estação favorita, em qualquer tempo.",
  "Cada dia é primavera quando estou com você.",
  "Te amo do jeito que só eu sei amar.",
  "Você é o melhor capítulo da minha história.",
  "Nosso amor não tem limites.",
  "Você me faz acreditar em amor eterno.",
  "Te amar é a coisa mais natural que eu faço.",
  "Você é meu mundo inteiro.",
  "Cada palavra sua é música pros meus ouvidos.",
  "Te amo em todas as línguas, em todas as formas.",
  "Você é a razão do meu sorriso bobo.",
  "Nosso amor é minha coisa mais preciosa.",
  "Você me completa de um jeito único.",
  "Cada lembrança com você é especial.",
  "Te amo mais do que cabem palavras.",
  "Você é minha casa, meu lar, meu lugar.",
  "Com você, descobri o que é amor de verdade.",
  "Cada 'eu te amo' meu é verdadeiro.",
  "Você é o amor da minha vida, hoje e sempre.",
  "Nosso amor é uma aventura linda.",
  "Te amar é minha atividade favorita.",
  "Você me faz feliz de um jeito inexplicável.",
  "Cada dia com você é um dia abençoado.",
  "Você é meu pensamento bom antes de dormir.",
  "Te amo do fundo do meu coração.",
  "Você é a melhor parte de mim.",
  "Nosso amor é a história mais bonita que eu conheço.",
  "Cada beijo seu é inesquecível.",
  "Te amo pra sempre, sem condições.",

  // Maio
  "Maio, e meu amor por você continua firme e forte.",
  "Você é minha paz em meio ao caos.",
  "Cada dia com você vale a pena.",
  "Te amo do jeito mais sincero que existe.",
  "Você é meu porto seguro.",
  "Nosso amor é a coisa mais linda que eu tenho.",
  "Você me faz acreditar em milagre.",
  "Cada abraço seu me recarrega.",
  "Te amar é a melhor parte do meu dia.",
  "Você é a resposta das minhas preces.",
  "Nosso amor é maior que qualquer distância.",
  "Você é minha alma gêmea, sem dúvida.",
  "Cada momento com você é único.",
  "Te amo com todo o meu coração.",
  "Você é o melhor presente que a vida me deu.",
  "Nosso amor não cabe em uma vida só.",
  "Você me faz sorrir sem motivo aparente.",
  "Cada palavra 'eu te amo' é pouco.",
  "Te amo mais do que tudo nesse mundo.",
  "Você é meu sonho realizado.",
  "Nosso amor é eterno, não tem fim.",
  "Você me faz acreditar que tudo é possível.",
  "Cada beijo seu é especial.",
  "Te amar é a coisa mais bonita da minha vida.",
  "Você é a pessoa que eu sempre quis.",
  "Nosso amor é a melhor coisa que existe.",
  "Você me faz acreditar em conto de fadas.",
  "Cada 'eu te amo' meu é mais verdadeiro.",
  "Te amo hoje e pra sempre.",
  "Você é meu para sempre.",
  "Maio termina, mas meu amor por você não.",

  // Junho
  "Junho chegou, e eu continuo te amando cada vez mais.",
  "Você é o amor da minha vida, sem comparação.",
  "Cada dia com você é um presente.",
  "Te amo do jeito que o coração pede.",
  "Você é minha pessoa favorita no universo.",
  "Nosso amor é a melhor coisa que me aconteceu.",
  "Você me faz acreditar em amor verdadeiro.",
  "Cada momento do seu lado é especial.",
  "Te amar é a coisa mais linda que eu faço.",
  "Você é meu tudo, meu mundo, minha vida.",
  "Nosso amor é uma história sem fim.",
  "Você me faz sorrir do jeito mais bobo.",
  "Cada 'eu te amo' é uma promessa.",
  "Te amo com toda a minha alma.",
  "Você é a melhor coisa que já me aconteceu.",
  "Nosso amor é maior que qualquer coisa.",
  "Você me faz acreditar em felizes para sempre.",
  "Cada beijo seu é o melhor presente.",
  "Te amar é o que eu sei fazer de melhor.",
  "Você é a pessoa mais incrível do mundo.",
  "Nosso amor é lindo, verdadeiro e eterno.",
  "Você me faz querer acordar todo dia.",
  "Cada palavra sua me faz sorrir.",
  "Te amo do jeito mais bonito que existe.",
  "Você é o significado da palavra amor pra mim.",
  "Nosso amor é a minha maior conquista.",
  "Você é a pessoa que eu escolho todo dia.",
  "Cada abraço seu é meu refúgio.",
  "Te amo mais do que as palavras podem dizer.",
  "Você é meu lar, onde quer que esteja.",

  // Julho
  "Julho, e meu amor por você continua firme.",
  "Você é a melhor parte da minha vida.",
  "Cada dia com você é inesquecível.",
  "Te amo com todo o meu ser.",
  "Você é meu sol, minha lua, minhas estrelas.",
  "Nosso amor é a coisa mais bonita que existe.",
  "Você me faz acreditar em amor eterno.",
  "Cada momento com você é mágico.",
  "Te amar é minha atividade favorita.",
  "Você é o amor da minha vida.",
  "Nosso amor é maior que o universo.",
  "Você me faz sorrir do jeito mais lindo.",
  "Cada 'eu te amo' é pouco.",
  "Te amo do fundo do meu coração.",
  "Você é a pessoa mais especial que eu conheço.",
  "Nosso amor é pra sempre.",
  "Você me faz acreditar em destinos.",
  "Cada beijo seu é inesquecível.",
  "Te amar é a melhor coisa que eu faço.",
  "Você é meu pensamento favorito.",
  "Nosso amor é uma história linda.",
  "Você me faz acreditar em milagres.",
  "Cada dia ao seu lado vale por mil.",
  "Te amo com todas as minhas forças.",
  "Você é a resposta de tudo.",
  "Nosso amor não tem explicação.",
  "Você me faz querer ser melhor.",
  "Cada abraço seu é o melhor abraço.",
  "Te amo hoje, amanhã e sempre.",
  "Você é meu para sempre favorito.",
  "Julho termina, mas meu amor não.",

  // Agosto
  "Agosto chegou, e eu te amo mais do que nunca.",
  "Você é a melhor coisa da minha vida.",
  "Cada dia com você é um presente.",
  "Te amo do jeito mais sincero.",
  "Você é meu porto seguro, sempre.",
  "Nosso amor é eterno e verdadeiro.",
  "Você me faz acreditar em amor de verdade.",
  "Cada momento com você é único.",
  "Te amar é a coisa mais linda.",
  "Você é meu tudo, literalmente.",
  "Nosso amor é a melhor história.",
  "Você me faz sorrir sem motivo.",
  "Cada 'eu te amo' meu é verdadeiro.",
  "Te amo com toda a minha alma.",
  "Você é a pessoa dos meus sonhos.",
  "Nosso amor não tem fim.",
  "Você me faz acreditar em felizes para sempre.",
  "Cada beijo seu é o melhor.",
  "Te amar é o que eu amo fazer.",
  "Você é a pessoa mais incrível do mundo.",
  "Nosso amor é lindo e verdadeiro.",
  "Você me faz querer viver mais.",
  "Cada palavra sua é especial.",
  "Te amo do jeito que só eu sei.",
  "Você é o amor da minha vida.",
  "Nosso amor é a coisa mais bonita.",
  "Você me faz acreditar em tudo.",
  "Cada abraço seu é o melhor.",
  "Te amo pra sempre, sem fim.",
  "Você é meu para sempre.",
  "Agosto se vai, meu amor fica.",

  // Setembro
  "Setembro chegou com mais amor por você.",
  "Você é a melhor parte do meu mundo.",
  "Cada dia com você é especial.",
  "Te amo com todo o meu coração.",
  "Você é minha paz, minha alegria.",
  "Nosso amor é a coisa mais linda.",
  "Você me faz acreditar em amor.",
  "Cada momento com você é mágico.",
  "Te amar é minha coisa favorita.",
  "Você é o amor da minha vida.",
  "Nosso amor é eterno, sempre.",
  "Você me faz sorrir de verdade.",
  "Cada 'eu te amo' é pouco.",
  "Te amo do fundo da minha alma.",
  "Você é a pessoa mais especial.",
  "Nosso amor é pra toda vida.",
  "Você me faz acreditar em tudo.",
  "Cada beijo seu é inesquecível.",
  "Te amar é o melhor que eu faço.",
  "Você é a pessoa dos meus sonhos.",
  "Nosso amor é lindo, ponto.",
  "Você me faz querer ser melhor.",
  "Cada palavra sua é música.",
  "Te amo do jeito mais lindo.",
  "Você é meu tudo, sempre.",
  "Nosso amor é a maior verdade.",
  "Você me faz acreditar em almas gêmeas.",
  "Cada abraço seu é lar.",
  "Te amo hoje e sempre.",
  "Você é meu para sempre favorito.",

  // Outubro
  "Outubro chegou, e meu amor por você continua.",
  "Você é a melhor coisa que existe na minha vida.",
  "Cada dia com você é abençoado.",
  "Te amo com todas as minhas forças.",
  "Você é meu sol em qualquer estação.",
  "Nosso amor é lindo e verdadeiro.",
  "Você me faz acreditar em amor.",
  "Cada momento com você é único.",
  "Te amar é a coisa mais bonita.",
  "Você é o amor da minha vida.",
  "Nosso amor não tem fim.",
  "Você me faz sorrir sempre.",
  "Cada 'eu te amo' é verdadeiro.",
  "Te amo com toda a minha alma.",
  "Você é minha pessoa favorita.",
  "Nosso amor é pra sempre.",
  "Você me faz acreditar em tudo.",
  "Cada beijo seu é especial.",
  "Te amar é o que eu amo.",
  "Você é a pessoa dos meus sonhos.",
  "Nosso amor é a melhor coisa.",
  "Você me faz querer viver.",
  "Cada palavra sua é especial.",
  "Te amo do jeito que sei amar.",
  "Você é meu mundo inteiro.",
  "Nosso amor é a coisa mais linda.",
  "Você me faz acreditar em felicidade.",
  "Cada abraço seu é o melhor.",
  "Te amo pra sempre e sempre.",
  "Você é meu para sempre.",
  "Outubro se vai, eu te amo fica.",

  // Novembro
  "Novembro chegou, e eu te amo mais.",
  "Você é a melhor parte da minha vida.",
  "Cada dia com você é inesquecível.",
  "Te amo com todo o meu coração.",
  "Você é minha paz interior.",
  "Nosso amor é a coisa mais bonita.",
  "Você me faz acreditar em tudo.",
  "Cada momento com você é único.",
  "Te amar é o que eu amo fazer.",
  "Você é o amor da minha vida.",
  "Nosso amor é eterno e lindo.",
  "Você me faz sorrir sem parar.",
  "Cada 'eu te amo' é verdadeiro.",
  "Te amo com toda a minha alma.",
  "Você é minha pessoa especial.",
  "Nosso amor é pra toda vida.",
  "Você me faz acreditar em amor.",
  "Cada beijo seu é o melhor.",
  "Te amar é minha coisa favorita.",
  "Você é a pessoa dos meus sonhos.",
  "Nosso amor é lindo, sempre.",
  "Você me faz querer ser melhor.",
  "Cada palavra sua é linda.",
  "Te amo do fundo do coração.",
  "Você é meu tudo, sempre.",
  "Nosso amor é a maior verdade.",
  "Você me faz acreditar em nós.",
  "Cada abraço seu é especial.",
  "Te amo hoje e sempre.",
  "Você é meu para sempre.",

  // Dezembro
  "Dezembro chegou, e eu te amo mais ainda.",
  "Você é a melhor coisa da minha vida.",
  "Cada dia com você é um presente.",
  "Te amo com todas as minhas forças.",
  "Você é meu lar, sempre.",
  "Nosso amor é a coisa mais linda.",
  "Você me faz acreditar em amor.",
  "Cada momento com você é mágico.",
  "Te amar é o melhor de tudo.",
  "Você é o amor da minha vida.",
  "Nosso amor é eterno, sempre.",
  "Você me faz sorrir sempre.",
  "Cada 'eu te amo' é verdadeiro.",
  "Te amo com toda a minha alma.",
  "Você é a pessoa mais especial.",
  "Nosso amor é pra sempre.",
  "Você me faz acreditar em tudo.",
  "Cada beijo seu é inesquecível.",
  "Te amar é o que eu amo.",
  "Você é a pessoa dos meus sonhos.",
  "Nosso amor é a coisa mais bonita.",
  "Você me faz feliz de verdade.",
  "Cada palavra sua é especial.",
  "Te amo do jeito mais lindo.",
  "Você é meu mundo, sempre.",
  "Nosso amor é a maior verdade.",
  "Você me faz acreditar em tudo.",
  "Cada abraço seu é o melhor.",
  "Te amo pra sempre, sem fim.",
  "Você é meu para sempre.",
  "Dezembro termina, nosso amor não. ♡"
];

// Pega a mensagem baseado no dia do ano (1-365)
function getMensagemDoDia() {
  const hoje = new Date();
  const inicio = new Date(hoje.getFullYear(), 0, 0);
  const diff = (hoje - inicio) + ((hoje.getTimezoneOffset() - inicio.getTimezoneOffset()) * 60 * 1000);
  const diaDoAno = Math.floor(diff / (1000 * 60 * 60 * 24));
  const idx = (diaDoAno - 1) % MENSAGENS.length;
  return MENSAGENS[idx];
}
