// ============================================
// MENSAGENS — 365 mensagens do Rafael pra Fernanda
// Inspiradas na história de vocês (inspiração, não cópia)
// Voz dele: "minha princesa", "minha pequena", direto, sem firula
// ============================================

const MENSAGENS = [
  // ============== JANEIRO (31 msgs) — beijo, ano novo, recomeço ==============
  "Faz 13 anos que o ano virou diferente. Continua sendo o melhor presente da minha vida. Te amo, minha pequena. ♡",
  "01 de janeiro. A data que eu não esqueço nunca. Obrigado por esse beijo que mudou tudo. 💋",
  "Cada réveillon depois daquele, eu só penso: obrigado por ter ficado.",
  "Se eu pudesse escolher um momento pra repetir pra sempre, seria aquele 23h de 01/01/2013.",
  "Fernanda, você é o único motivo de eu não reclamar do ano que começa cedo. 😅",
  "Obrigado por mais um ano do seu lado. E pelos próximos que virão.",
  "Janeiro de 2013 foi o mês que minha vida virou do avesso. Do avesso bom. Do avesso certo.",
  "Dizem que começo de ano é pra mudar. Eu só quero continuar do seu lado.",
  "Meu primeiro pensamento hoje foi você. De novo. E amanhã igual. 💕",
  "Você é meu réveillon favorito. Todo dia começa quando acordo e lembro de você.",
  "Treze anos depois, eu ainda fico nervoso perto de você. Do bom jeito.",
  "Se depender de mim, ano que vem é igual: eu, você, e a gente.",
  "Prometo te amar mais esse ano do que no ano passado. (Topa o desafio?)",
  "Você é o tipo de pessoa que faz janeiro valer a pena.",
  "01/01 é a nossa data. Não precisa de mais nenhuma.",
  "Acordei pensando em você e no quanto eu te amo. Rotina bonita a nossa. 💖",
  "Cada dia 01 eu celebro duas coisas: o ano novo e o nosso começo.",
  "Fernanda, se eu te conto há quantos anos te amo, dá um número grande. Mas o amor tá sempre igual: imenso.",
  "Amo a gente. Amo o que a gente construiu. Amo o que ainda vem. ✨",
  "Janeiro vai rápido. Mas o que eu sinto por você vai demorado, pra sempre.",
  "Você me perguntou outro dia por que eu te amo. A resposta continua a mesma: é você. Sempre foi.",
  "Meu amor, prometo que esse ano vai ter mais abraço, menos tela, mais a gente. 🤞",
  "Cada vez que você ri, eu lembro do porquê de tudo.",
  "Fernanda, a gente já passou tanta coisa que eu sei: pra gente, o que vier, a gente resolve.",
  "Hoje eu te amo do jeito mais bonito que eu consigo. Que é pouco perto do que sinto.",
  "Prometo que vou te olhar como se fosse a primeira vez, todos os dias. Olha que promessa difícil. Não é.",
  "Cuidar de você é a coisa que eu mais gosto de fazer no mundo.",
  "Você é a resposta que eu nem sabia que tinha feito a pergunta. 💕",
  "01 de janeiro de 2027 vai chegar, e eu vou tá do seu lado. De novo.",
  "Obrigado por ser o meu recomeço favorito. 💍",
  "Janeiro, pra mim, é só mais um mês pra te amar. Mas com o nosso brinde.",

  // ============== FEVEREIRO (28 msgs) — mês do amor (a data deles é junho) ==============
  "Fevereiro chega e o mundo fala de amor. Eu só penso: eu sei amar de verdade, eu tenho você. 💘",
  "Não precisa de 12 de junho pra eu te amar mais. Mas em fevereiro eu lembro que essa data é nossa também.",
  "Fernanda, te amo do jeito que só a gente entende.",
  "Mês do amor, e meu amor é você. O resto é o resto. 💖",
  "Se eu te der um presente em fevereiro, vai ser o mesmo de sempre: meu coração. Não aceito devolução.",
  "Você é meu Valentine de janeiro a dezembro. Mas em fevereiro eu gosto de falar mais. 😊",
  "Amor de verdade não tem data, mas em fevereiro eu gosto de celebrar o nosso. ♡",
  "Fernanda, você me ensinou o que é amar no silêncio, no barulho, no fácil, no difícil. 💕",
  "Prometo ser o cara que te faz sorrir hoje e daqui 50 anos. Topa?",
  "Nosso amor não é de filme, é de verdade. Por isso é mais bonito.",
  "Em fevereiro, eu amo mais ainda. Se é que isso é possível.",
  "Você é meu tipo favorito de amor: o que escolhe ficar. ✨",
  "Cada 'eu te amo' meu é igual ao primeiro. Talvez até mais verdadeiro.",
  "Fernanda, se eu te escrever mil mensagens, todas vão dizer a mesma coisa: te amo. ♡",
  "Mês do amor. E o meu é uma mulher incrível chamada Fernanda.",
  "A gente não precisa de data pra se amar. Mas em fevereiro eu gosto de fingir que é a primeira vez. 😄",
  "Você me faz acreditar em tudo. Principalmente em amor.",
  "Amor de carnaval é fantasia. O nosso é pra vida inteira.",
  "Fernanda, te amo do jeito que o coração aguenta. E ele aguenta muito. 💖",
  "A melhor parte do meu dia é saber que você existe.",
  "Prometo: vou te amar em fevereiro, em março, em todos os meses.",
  "Você é meu para sempre favorito. Até quando? Pra sempre. ✨",
  "Em fevereiro, eu celebro a mulher que me faz acreditar em nós.",
  "Fernanda, você é a melhor parte da minha história. A única que eu não mudaria.",
  "Cada dia com você é um presente. Mas em fevereiro o presente vem embrulhado em coração. 🎁",
  "Você é meu Valentine de verdade. O resto é só comercial. 💘",
  "Amor, em fevereiro eu te amo do jeito que eu te amo o ano todo: muito.",
  "Obrigado por ser o amor da minha vida. 12 de junho é nosso, mas fevereiro também. 😊",

  // ============== MARÇO (31 msgs) — aniversário dele, pedido de namoro dela ==============
  "23 de março é o dia do meu aniversário. Mas o melhor presente eu ganhei quando você me pediu em namoro. 💍",
  "Você me pediu em namoro. Melhor presente. Melhor decisão. Melhor você. 💖",
  "Março, pra mim, é o mês que começou tudo. Oficialmente.",
  "Fernanda, naquele 23 de março, minha resposta foi sim. Continua sendo sim, 13 anos depois. 💍",
  "Aniversário, pra mim, é só mais um motivo pra agradecer por ter você.",
  "Amo como você me faz rir no meu aniversário. Amo como me faz rir o resto do ano todo.",
  "Você é o tipo de presente que não se compra, não se embrulha, não se troca.",
  "23 de março. Minha data favorita. Por causa de uma pergunta sua. 💍",
  "Fernanda, meu niver é só um dia. Te amar é pra vida toda. Mas no dia 23 eu celebro as duas coisas. ♡",
  "A gente tá junto há tanto tempo que a pergunta já virou resposta: sim, mil vezes sim.",
  "Você me pediu em namoro, e eu fui o sortudo ali.",
  "Março é o mês que eu celebro você, oficialmente. 💕",
  "Obrigado por ser a mulher que me pediu em namoro. Corajosa e linda.",
  "23/03, o dia que minha vida virou do jeito certo. Pra sempre.",
  "Se eu pudesse voltar naquele 23 de março, eu responderia sim mais rápido. 😊",
  "Fernanda, você me deu o melhor presente do meu niver: um pra sempre. 💍",
  "Aniversário, dia dos namorados, réveillon. Todas as datas são nossas. ✨",
  "Março, pra mim, é só o mês que começou o 'nós'. E o 'nós' continua lindo.",
  "Você me pediu em namoro, e eu te peço em casamento todo dia (sem falar, mas penso). 😊",
  "Fernanda, a gente tá junto há tanto tempo que já é da família. Sempre foi. 💕",
  "Obrigado por me fazer o homem mais sortudo do mundo, todo 23 de março.",
  "Março, o mês que eu lembro que o 'sim' foi a melhor palavra que eu disse.",
  "Você me pediu em namoro, e eu te peço todo dia pra ficar. Pra sempre.",
  "Amo como a gente lembra de cada data. Mas o que importa é a gente. 💖",
  "23/03, 01/01, 12/06. As datas mudam. O amor não. ✨",
  "Março chegou, e eu te amo mais ainda. Se é que tem como. 💕",
  "Fernanda, a gente já é família há tanto tempo que eu nem lembro como era antes.",
  "Você me pediu em namoro, e eu te peço todo dia: fica. Pra sempre. 💍",
  "Aniversário meu, namoro nosso. Melhor assim. 😊",
  "Março, o mês que começou a aventura. E que aventura boa. ♡",
  "Fernanda, 13 anos de 'sim'. E contando.",

  // ============== ABRIL (30 msgs) — amor cotidiano, piadas, cumplicidade ==============
  "Amor, hoje eu acordei pensando em uma coisa: como você é incrível. E como eu tenho sorte.",
  "Você é o tipo de pessoa que faz o dia ficar leve só de existir. ☀️",
  "Fernanda, obrigada por me aguentar. (Ou por fingir que aguenta. Tanto faz, te amo.) 😄",
  "Cada dia com você é uma piada que só a gente entende. E eu adoro.",
  "Prometo: vou te fazer rir hoje. E amanhã. E depois. E depois. Pra sempre. 😊",
  "Amo a forma como você me olha. Como se eu fosse incrível. Eu vou fingir que acredito.",
  "Fernanda, se eu te conto quantas vezes eu penso em você por dia, dá vergonha. Mas é verdade. 💕",
  "Obrigado por ser minha parceira de vida, de briga, de tudo.",
  "Você me faz rir sem nem tentar. Isso é talento. 💖",
  "Cada manhã com você é um presente. Principalmente quando você traz café. ☕",
  "Fernanda, a gente já passou por tanta coisa que eu sei: a gente é imbatível. 💪",
  "Amo a forma como a gente se conhece. Até os defeitos. Principalmente os defeitos. 😄",
  "Você me faz acreditar que amor de verdade existe. Porque eu vivo ele todo dia.",
  "Hoje eu te amo do jeito mais comum do mundo. Mas é o meu jeito de sempre. ♡",
  "Fernanda, obrigada por ser exatamente quem você é. Não muda nunca. ✨",
  "Prometo te amar mais um dia. E mais um. E mais um. Até cansar. (Não vai cansar.)",
  "Você é meu lugar favorito no mundo. Mesmo quando tá do meu lado reclamando. 😅",
  "Cada dia com você é o melhor dia. Mesmo o dia ruim. Até o ruim é bom com você.",
  "Fernanda, te amo do jeito que dá. Mas dá muito. 💕",
  "A gente já é tão junto que até o silêncio é bonito. 🤫",
  "Você me ensinou que amor também é lavar louça junto. (E eu aceito.) 😄",
  "Amo a forma como a gente cresce junto. Mesmo quando tá difícil.",
  "Fernanda, você é a pessoa que eu quero do lado quando tudo dá certo. E quando dá errado também.",
  "Hoje eu te amo. Amanhã eu te amo. Depois eu te amo. (Já entendeu, né?)",
  "Obrigado por me fazer acreditar que a gente pode tudo. A gente pode. 💪",
  "Fernanda, a gente é a melhor dupla que eu conheço. E olha que eu te conheço bem. 😊",
  "Você é a resposta pra tudo. Tipo: o que a gente janta? 'Você escolhe, amor.' Resolve. 😄",
  "Cada dia com você é um capítulo novo. E eu não quero parar de ler. 📖",
  "Fernanda, te amo do jeito que eu sei amar: torto, mas verdadeiro. ♡",
  "Obrigado por ser o tipo de mulher que não desiste da gente. (Porque eu também não.)",

  // ============== MAIO (31 msgs) — pré-aniversário dela, planos, futuro ==============
  "Maio chegou, e eu te amo mais ainda. Se é que tem limite. (Não tem.)",
  "Fernanda, faltam poucas semanas pro seu dia. Mas eu celebro você todo dia. 💕",
  "Cada dia com você é preparação pro seu aniversário. Mas o presente é você. 😊",
  "Amo como a gente planeja futuro junto. E o futuro é lindo porque tem você.",
  "Fernanda, a gente já tem uma história. Mas a melhor parte ainda tá por vir. ✨",
  "Hoje eu te amo do jeito que vai te amar daqui 50 anos. Igual. 💖",
  "Prometo cuidar de você hoje, amanhã, e sempre. (Assino embaixo.) 📝",
  "Você é o tipo de mulher que faz a gente querer ser melhor. E eu quero ser melhor pra você.",
  "Fernanda, a gente já passou por tanta coisa que a gente é imbatível. 💪",
  "Amo a forma como a gente envelhece junto. Cada dia mais bonito. ♡",
  "Você me faz acreditar no 'pra sempre'. E o 'pra sempre' tem seu nome. ✨",
  "Fernanda, a gente já tem uma família. E é a melhor que eu poderia ter. 💕",
  "Cada dia com você é a confirmação de que eu escolhi certo. (E escolheria de novo.)",
  "Obrigado por ser minha parceira de vida, de briga, de tudo. 💖",
  "Fernanda, a gente já é tão junto que até o CPF é par (mentira, mas quase). 😄",
  "Você é o tipo de pessoa que faz a vida valer a pena. Sério.",
  "Amo a forma como a gente cuida um do outro. Mesmo no silêncio. 🤫",
  "Fernanda, a gente é a prova de que amor de verdade existe. E funciona. 💍",
  "Hoje eu te amo. Amanhã eu te amo. Em maio, junho, todos os meses. ♡",
  "Você é a mulher que me faz querer ser o melhor pai, o melhor marido, o melhor tudo. 💪",
  "Fernanda, obrigada por fazer parte da minha história. Você é a melhor parte.",
  "Amo a forma como a gente enfrenta as coisas juntos. Hospital, briga, qualquer coisa. 💕",
  "Você é meu hoje e meu amanhã. E meu depois também. ✨",
  "Fernanda, a gente já passou tanta coisa que eu sei: o que vier, a gente resolve. 💪",
  "Cada dia com você é um voto que eu renovo. (Mas sem padre, só com a gente. 😄)",
  "Você me faz acreditar em tudo. Em amor, em família, em pra sempre. 💖",
  "Fernanda, te amo do jeito que eu sei amar: muito. (E ainda tá pouco.) ♡",
  "Obrigado por me fazer o homem que eu sou. Você é a melhor parte de mim. ✨",
  "Amo a forma como a gente cresce junto. Cada dia mais. 🌱",
  "Fernanda, a gente é a prova de que opostos se atraem. (Porque eu sou legal e você... também. 😄)",
  "Você é meu pra sempre favorito. Até quando? Até cansar. (Não vai cansar.) 💍",

  // ============== JUNHO (30 msgs) — dia dos namorados, a data principal ==============
  "12 de junho. O dia mais bonito do calendário. O nosso dia. ♡",
  "Feliz Dia dos Namorados, meu amor. Você é a melhor escolha da minha vida. 💖",
  "12 de junho de 2013. A data que mudou tudo. E continua mudando. Pra melhor.",
  "Fernanda, hoje é o nosso dia. Mas te amo em todos os outros 364. 💕",
  "Você é o amor da minha vida. Hoje, amanhã, e depois. (Em maiúsculo: SEMPRE.) ✨",
  "Feliz Dia dos Namorados pra mulher mais incrível que eu conheço. Você. 💘",
  "12/06, a data que a gente transformou em 'a nossa'. E continua sendo. 🌹",
  "Fernanda, te amo do jeito que só a gente entende. E isso é o suficiente. ♡",
  "Obrigado por 12 de junhos com você. E pelos próximos que virão. 💖",
  "Você é meu Valentine de janeiro a dezembro. Mas em 12 de junho eu lembro mais ainda. 💕",
  "Fernanda, se eu pudesse voltar naquele 12 de junho de 2013, faria tudo igual. E melhor. ✨",
  "Feliz Dia dos Namorados, meu amor. Você é o melhor presente que a vida me deu. 🎁",
  "12/06, a data que eu celebro a mulher que me fez acreditar em amor. 💖",
  "Fernanda, hoje e sempre, você é minha. E eu sou seu. Pra sempre. 💍",
  "O melhor Dia dos Namorados é o que eu passo com você. Todos eles. ♡",
  "Fernanda, te amo do jeito que a gente ama: sem medida, sem fim, sem data pra parar. 💕",
  "12 de junho, o dia que o amor virou compromisso. E continua sendo, com orgulho. 💍",
  "Feliz Dia dos Namorados, minha princesa. Você é tudo pra mim. 👑",
  "Fernanda, 12/06 é o nosso dia. Mas você é minha todo dia. 💖",
  "Você me pediu em namoro em março. Em junho a gente celebrou. E continua celebrando. ✨",
  "Fernanda, obrigada por cada 12 de junho. E pelos próximos. ♡",
  "Feliz Dia dos Namorados, minha pequena. Você é o amor da minha vida. 💕",
  "12/06, a data que eu mais gosto. Porque é nossa. 💖",
  "Fernanda, se amor desse dinheiro, a gente era rico. Mas o que a gente tem é melhor. ✨",
  "Obrigado por ser a mulher que faz 12 de junho valer a pena. Todo ano. ♡",
  "Fernanda, te amo do jeito que o dia 12 merece: muito. 💘",
  "Feliz Dia dos Namorados, meu amor. Você é a melhor parte de mim. 💕",
  "12 de junho, o dia que a gente parou de fingir que era só amizade. (Obrigado, beijo. 😄)",
  "Fernanda, você é meu pra sempre. E 12/06 é só mais um motivo pra lembrar. 💍",
  "Feliz Dia dos Namorados, minha rainha. Você é a melhor escolha da minha vida. 👑",
  "12/06, a data que eu celebro você. E a vida, por ter você. 💖",

  // ============== JULHO (31 msgs) — meio de ano, amor firme ==============
  "Julho chegou, e eu te amo do mesmo jeito: muito. (Mas sempre cabe mais.)",
  "Fernanda, meio de ano. A gente tá junto há 13. E cada vez mais. 💕",
  "Obrigado por ser a mulher que faz julho valer a pena. (E todos os meses.) ✨",
  "Você é meu amor de julho, de janeiro, de sempre. ♡",
  "Amo a forma como a gente continua, mesmo quando o mundo muda. (E o mundo muda muito.)",
  "Fernanda, a gente já é tão junto que até briga a gente resolve bem. 😅",
  "Você me faz acreditar que amor de verdade dura. Porque o nosso dura. 💪",
  "Cada dia com você é uma nova chance de te amar mais. (E eu não perco a chance.) 💕",
  "Fernanda, te amo do jeito que eu te amo o ano todo: torto, mas verdadeiro. ♡",
  "Obrigado por me fazer o homem que eu sou. Você é a melhor parte. ✨",
  "Você é o tipo de mulher que faz o mês valer a pena. Mas é a vida toda que vale. 💖",
  "Fernanda, a gente é a prova de que amor de verdade funciona. 13 anos depois. 💍",
  "Cada dia com você é a confirmação de que eu escolhi certo. (E escolheria de novo.)",
  "Amo a forma como a gente se conhece. Até os defeitos. (Principalmente os defeitos. 😄)",
  "Fernanda, te amo do jeito que dá. Mas dá muito. 💕",
  "Você é meu hoje e meu amanhã. E meu depois também. ♡",
  "Obrigado por ser o tipo de mulher que não desiste. (Porque eu também não.) 💪",
  "Fernanda, a gente já passou tanta coisa que eu sei: a gente é imbatível. ✨",
  "Amo a forma como a gente cresce junto. Mesmo quando tá difícil. 🌱",
  "Você é o amor da minha vida. De julho, de janeiro, de sempre. 💖",
  "Fernanda, a gente já é família há tanto tempo que eu nem lembro como era antes. ♡",
  "Cada dia com você é um presente. Principalmente o dia a dia. (Que é o melhor.)",
  "Obrigado por fazer de mim um homem melhor. Você é a melhor parte da minha história. ✨",
  "Fernanda, te amo do jeito que eu sei amar: muito. (E ainda tá pouco.) 💕",
  "Você é meu pra sempre favorito. (Até quando? Pra sempre.) 💍",
  "Amo a forma como a gente cuida um do outro. Mesmo no silêncio. 🤫",
  "Fernanda, a gente é a prova de que opostos se atraem. (Porque eu sou legal. 😄)",
  "Cada dia com você é a confirmação de que amor de verdade existe. E funciona. 💖",
  "Obrigado por ser minha parceira de vida, de briga, de tudo. ♡",
  "Fernanda, a gente já é tão junto que até o silêncio é bonito. E o barulho também. 😊",
  "Você é meu amor de julho. De janeiro. De sempre. ✨",

  // ============== AGOSTO (31 msgs) — meio de segundo semestre, amor cotidiano ==============
  "Agosto chegou, e eu te amo mais ainda. (Se é que tem limite. Não tem.)",
  "Fernanda, a gente tá junto há 13 anos. E cada vez mais bonito. 💕",
  "Obrigado por ser a mulher que faz agosto valer a pena. (E todos os meses.) ✨",
  "Você é meu amor de agosto, de janeiro, de sempre. ♡",
  "Amo a forma como a gente continua, firme, forte, junto. 💪",
  "Fernanda, a gente já é tão junto que até a briga é bonita. (Às vezes. 😄)",
  "Você me faz acreditar que amor de verdade dura. Porque o nosso dura. 💍",
  "Cada dia com você é uma nova chance de te amar mais. 💕",
  "Fernanda, te amo do jeito que eu te amo o ano todo: muito. ✨",
  "Obrigado por me fazer o homem que eu sou. Você é a melhor parte. ♡",
  "Você é o tipo de mulher que faz o mês valer a pena. Mas é a vida toda que vale. 💖",
  "Fernanda, a gente é a prova de que amor de verdade funciona. 13 anos depois. 💍",
  "Cada dia com você é a confirmação de que eu escolhi certo. (E escolheria de novo.)",
  "Amo a forma como a gente se conhece. Até os defeitos. (Principalmente os defeitos. 😄)",
  "Fernanda, te amo do jeito que dá. Mas dá muito. 💕",
  "Você é meu hoje e meu amanhã. E meu depois também. ♡",
  "Obrigado por ser o tipo de mulher que não desiste. (Porque eu também não.) 💪",
  "Fernanda, a gente já passou tanta coisa que eu sei: a gente é imbatível. ✨",
  "Amo a forma como a gente cresce junto. Mesmo quando tá difícil. 🌱",
  "Você é o amor da minha vida. De agosto, de janeiro, de sempre. 💖",
  "Fernanda, a gente já é família há tanto tempo que eu nem lembro como era antes. ♡",
  "Cada dia com você é um presente. Principalmente o dia a dia.",
  "Obrigado por fazer de mim um homem melhor. Você é a melhor parte da minha história. ✨",
  "Fernanda, te amo do jeito que eu sei amar: muito. (E ainda tá pouco.) 💕",
  "Você é meu pra sempre favorito. (Até quando? Pra sempre.) 💍",
  "Amo a forma como a gente cuida um do outro. Mesmo no silêncio. 🤫",
  "Fernanda, a gente é a prova de que opostos se atraem. (Porque eu sou legal. 😄)",
  "Cada dia com você é a confirmação de que amor de verdade existe. E funciona. 💖",
  "Obrigado por ser minha parceira de vida, de briga, de tudo. ♡",
  "Fernanda, a gente já é tão junto que até o silêncio é bonito. E o barulho também. 😊",
  "Você é meu amor de agosto. De janeiro. De sempre. ✨",

  // ============== SETEMBRO (30 msgs) — primavera, flores, renovação ==============
  "Setembro chegou, e a gente floresce junto. A cada dia mais. 🌸",
  "Fernanda, a primavera começa, e meu amor por você só cresce. (Sempre cabe mais.)",
  "Obrigado por ser a mulher que faz setembro valer a pena. (E todos os meses.) ✨",
  "Você é meu amor de setembro, de janeiro, de sempre. ♡",
  "Amo a forma como a gente continua, firme, forte, junto, mesmo quando a vida muda. 💪",
  "Fernanda, a gente já é tão junto que até a briga é bonita. (Às vezes. 😄)",
  "Você me faz acreditar que amor de verdade dura. Porque o nosso dura. 💍",
  "Cada dia com você é uma nova chance de te amar mais. 💕",
  "Fernanda, te amo do jeito que eu te amo o ano todo: muito. ✨",
  "Obrigado por me fazer o homem que eu sou. Você é a melhor parte. ♡",
  "Você é o tipo de mulher que faz o mês valer a pena. Mas é a vida toda que vale. 💖",
  "Fernanda, a gente é a prova de que amor de verdade funciona. 13 anos depois. 💍",
  "Cada dia com você é a confirmação de que eu escolhi certo. (E escolheria de novo.)",
  "Amo a forma como a gente se conhece. Até os defeitos. (Principalmente os defeitos. 😄)",
  "Fernanda, te amo do jeito que dá. Mas dá muito. 💕",
  "Você é meu hoje e meu amanhã. E meu depois também. ♡",
  "Obrigado por ser o tipo de mulher que não desiste. (Porque eu também não.) 💪",
  "Fernanda, a gente já passou tanta coisa que eu sei: a gente é imbatível. ✨",
  "Amo a forma como a gente cresce junto. Mesmo quando tá difícil. 🌱",
  "Você é o amor da minha vida. De setembro, de janeiro, de sempre. 💖",
  "Fernanda, a gente já é família há tanto tempo que eu nem lembro como era antes. ♡",
  "Cada dia com você é um presente. Principalmente o dia a dia.",
  "Obrigado por fazer de mim um homem melhor. Você é a melhor parte da minha história. ✨",
  "Fernanda, te amo do jeito que eu sei amar: muito. (E ainda tá pouco.) 💕",
  "Você é meu pra sempre favorito. (Até quando? Pra sempre.) 💍",
  "Amo a forma como a gente cuida um do outro. Mesmo no silêncio. 🤫",
  "Fernanda, a gente é a prova de que opostos se atraem. (Porque eu sou legal. 😄)",
  "Cada dia com você é a confirmação de que amor de verdade existe. E funciona. 💖",
  "Obrigado por ser minha parceira de vida, de briga, de tudo. ♡",
  "Fernanda, a gente já é tão junto que até o silêncio é bonito. E o barulho também. 😊",
  "Você é meu amor de setembro. De janeiro. De sempre. ✨",

  // ============== OUTUBRO (31 msgs) — outono, cores quentes, amor maduro ==============
  "Outubro chegou, e a gente amadurece junto. A cada dia mais. 🍂",
  "Fernanda, as folhas caem, mas o nosso amor só cresce. (Sempre.)",
  "Obrigado por ser a mulher que faz outubro valer a pena. (E todos os meses.) ✨",
  "Você é meu amor de outubro, de janeiro, de sempre. ♡",
  "Amo a forma como a gente continua, firme, forte, junto. 💪",
  "Fernanda, a gente já é tão junto que até a briga é bonita. (Às vezes. 😄)",
  "Você me faz acreditar que amor de verdade dura. Porque o nosso dura. 💍",
  "Cada dia com você é uma nova chance de te amar mais. 💕",
  "Fernanda, te amo do jeito que eu te amo o ano todo: muito. ✨",
  "Obrigado por me fazer o homem que eu sou. Você é a melhor parte. ♡",
  "Você é o tipo de mulher que faz o mês valer a pena. Mas é a vida toda que vale. 💖",
  "Fernanda, a gente é a prova de que amor de verdade funciona. 13 anos depois. 💍",
  "Cada dia com você é a confirmação de que eu escolhi certo. (E escolheria de novo.)",
  "Amo a forma como a gente se conhece. Até os defeitos. (Principalmente os defeitos. 😄)",
  "Fernanda, te amo do jeito que dá. Mas dá muito. 💕",
  "Você é meu hoje e meu amanhã. E meu depois também. ♡",
  "Obrigado por ser o tipo de mulher que não desiste. (Porque eu também não.) 💪",
  "Fernanda, a gente já passou tanta coisa que eu sei: a gente é imbatível. ✨",
  "Amo a forma como a gente cresce junto. Mesmo quando tá difícil. 🌱",
  "Você é o amor da minha vida. De outubro, de janeiro, de sempre. 💖",
  "Fernanda, a gente já é família há tanto tempo que eu nem lembro como era antes. ♡",
  "Cada dia com você é um presente. Principalmente o dia a dia.",
  "Obrigado por fazer de mim um homem melhor. Você é a melhor parte da minha história. ✨",
  "Fernanda, te amo do jeito que eu sei amar: muito. (E ainda tá pouco.) 💕",
  "Você é meu pra sempre favorito. (Até quando? Pra sempre.) 💍",
  "Amo a forma como a gente cuida um do outro. Mesmo no silêncio. 🤫",
  "Fernanda, a gente é a prova de que opostos se atraem. (Porque eu sou legal. 😄)",
  "Cada dia com você é a confirmação de que amor de verdade existe. E funciona. 💖",
  "Obrigado por ser minha parceira de vida, de briga, de tudo. ♡",
  "Fernanda, a gente já é tão junto que até o silêncio é bonito. E o barulho também. 😊",
  "Você é meu amor de outubro. De janeiro. De sempre. ✨",

  // ============== NOVEMBRO (30 msgs) — gratidão, pré-réveillon ==============
  "Novembro chegou, e eu sou grato por você. A cada dia mais. 🙏",
  "Fernanda, faltam poucas semanas pro fim do ano. E eu quero fechar mais um do seu lado. 💕",
  "Obrigado por ser a mulher que faz novembro valer a pena. (E todos os meses.) ✨",
  "Você é meu amor de novembro, de janeiro, de sempre. ♡",
  "Amo a forma como a gente continua, firme, forte, junto. 💪",
  "Fernanda, a gente já é tão junto que até a briga é bonita. (Às vezes. 😄)",
  "Você me faz acreditar que amor de verdade dura. Porque o nosso dura. 💍",
  "Cada dia com você é uma nova chance de te amar mais. 💕",
  "Fernanda, te amo do jeito que eu te amo o ano todo: muito. ✨",
  "Obrigado por me fazer o homem que eu sou. Você é a melhor parte. ♡",
  "Você é o tipo de mulher que faz o mês valer a pena. Mas é a vida toda que vale. 💖",
  "Fernanda, a gente é a prova de que amor de verdade funciona. 13 anos depois. 💍",
  "Cada dia com você é a confirmação de que eu escolhi certo. (E escolheria de novo.)",
  "Amo a forma como a gente se conhece. Até os defeitos. (Principalmente os defeitos. 😄)",
  "Fernanda, te amo do jeito que dá. Mas dá muito. 💕",
  "Você é meu hoje e meu amanhã. E meu depois também. ♡",
  "Obrigado por ser o tipo de mulher que não desiste. (Porque eu também não.) 💪",
  "Fernanda, a gente já passou tanta coisa que eu sei: a gente é imbatível. ✨",
  "Amo a forma como a gente cresce junto. Mesmo quando tá difícil. 🌱",
  "Você é o amor da minha vida. De novembro, de janeiro, de sempre. 💖",
  "Fernanda, a gente já é família há tanto tempo que eu nem lembro como era antes. ♡",
  "Cada dia com você é um presente. Principalmente o dia a dia.",
  "Obrigado por fazer de mim um homem melhor. Você é a melhor parte da minha história. ✨",
  "Fernanda, te amo do jeito que eu sei amar: muito. (E ainda tá pouco.) 💕",
  "Você é meu pra sempre favorito. (Até quando? Pra sempre.) 💍",
  "Amo a forma como a gente cuida um do outro. Mesmo no silêncio. 🤫",
  "Fernanda, a gente é a prova de que opostos se atraem. (Porque eu sou legal. 😄)",
  "Cada dia com você é a confirmação de que amor de verdade existe. E funciona. 💖",
  "Obrigado por ser minha parceira de vida, de briga, de tudo. ♡",
  "Fernanda, a gente já é tão junto que até o silêncio é bonito. E o barulho também. 😊",
  "Você é meu amor de novembro. De janeiro. De sempre. ✨",

  // ============== DEZEMBRO (31 msgs) — fim de ano, primeiro natal, primeiro réveillon ==============
  "Dezembro chegou, e eu te amo mais ainda. (Se é que tem limite. Não tem.) 💕",
  "Fernanda, fim de ano é a melhor época. Porque é quando eu lembro de tudo que a gente passou. ✨",
  "Obrigado por ser a mulher que faz dezembro valer a pena. (E todos os meses.) 🎄",
  "Você virou meu presente em todas as datas. Principalmente em dezembro. 🎁",
  "Amo a forma como a gente termina mais um ano juntos. Firme, forte, junto. 💪",
  "Fernanda, a gente já passou por tanta coisa que eu sei: 2027 vai ser nosso também. 💍",
  "Você me faz acreditar que amor de verdade dura. Porque o nosso dura. ♡",
  "Cada dia com você é uma nova chance de te amar mais. 💕",
  "Fernanda, te amo do jeito que eu te amo o ano todo: muito. ✨",
  "Obrigado por me fazer o homem que eu sou. Você é a melhor parte. 🎄",
  "Você é o tipo de mulher que faz o mês valer a pena. Mas é a vida toda que vale. 💖",
  "Fernanda, a gente é a prova de que amor de verdade funciona. 13 anos depois. 💍",
  "Cada dia com você é a confirmação de que eu escolhi certo. (E escolheria de novo.)",
  "Amo a forma como a gente se conhece. Até os defeitos. (Principalmente os defeitos. 😄)",
  "Fernanda, te amo do jeito que dá. Mas dá muito. 💕",
  "Você é meu hoje e meu amanhã. E meu depois também. ♡",
  "Obrigado por ser o tipo de mulher que não desiste. (Porque eu também não.) 💪",
  "Fernanda, a gente já passou tanta coisa que eu sei: a gente é imbatível. ✨",
  "Amo a forma como a gente cresce junto. Mesmo quando tá difícil. 🌱",
  "Você é o amor da minha vida. De dezembro, de janeiro, de sempre. 💖",
  "Fernanda, a gente já é família há tanto tempo que eu nem lembro como era antes. ♡",
  "Cada dia com você é um presente. Principalmente o dia a dia.",
  "Obrigado por fazer de mim um homem melhor. Você é a melhor parte da minha história. ✨",
  "Fernanda, te amo do jeito que eu sei amar: muito. (E ainda tá pouco.) 💕",
  "Você é meu pra sempre favorito. (Até quando? Pra sempre.) 💍",
  "Amo a forma como a gente cuida um do outro. Mesmo no silêncio. 🤫",
  "Fernanda, a gente é a prova de que opostos se atraem. (Porque eu sou legal. 😄)",
  "Feliz Ano Novo, meu amor. Que 2027 seja tão lindo quanto 2013 foi. 🥂"
];


// Pega a mensagem baseado no dia do ano (1-365)
function getMensagemDoDia() {
  const hoje = new Date();
  const inicio = new Date(hoje.getFullYear(), 0, 0);
  const diff = (hoje - inicio) + ((hoje.getTimezoneOffset() - inicio.getTimezoneOffset()) * 60 * 1000);
  const diaDoAno = Math.floor(diff / (1000 * 60 * 60 * 24));
  const idx = (diaDoAno - 1) % MENSAGENS.length;
  return MENSAGENS[idx];
}
